/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PreviewImport } from './routes/preview'
import { Route as PartysetupImport } from './routes/party_setup'
import { Route as InitiativetrackerImport } from './routes/initiative_tracker'
import { Route as InitiativeplayerImport } from './routes/initiative_player'
import { Route as EncountersImport } from './routes/encounters'
import { Route as BuilderImport } from './routes/builder'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PreviewRoute = PreviewImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRoute,
} as any)

const PartysetupRoute = PartysetupImport.update({
  id: '/party_setup',
  path: '/party_setup',
  getParentRoute: () => rootRoute,
} as any)

const InitiativetrackerRoute = InitiativetrackerImport.update({
  id: '/initiative_tracker',
  path: '/initiative_tracker',
  getParentRoute: () => rootRoute,
} as any)

const InitiativeplayerRoute = InitiativeplayerImport.update({
  id: '/initiative_player',
  path: '/initiative_player',
  getParentRoute: () => rootRoute,
} as any)

const EncountersRoute = EncountersImport.update({
  id: '/encounters',
  path: '/encounters',
  getParentRoute: () => rootRoute,
} as any)

const BuilderRoute = BuilderImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderImport
      parentRoute: typeof rootRoute
    }
    '/encounters': {
      id: '/encounters'
      path: '/encounters'
      fullPath: '/encounters'
      preLoaderRoute: typeof EncountersImport
      parentRoute: typeof rootRoute
    }
    '/initiative_player': {
      id: '/initiative_player'
      path: '/initiative_player'
      fullPath: '/initiative_player'
      preLoaderRoute: typeof InitiativeplayerImport
      parentRoute: typeof rootRoute
    }
    '/initiative_tracker': {
      id: '/initiative_tracker'
      path: '/initiative_tracker'
      fullPath: '/initiative_tracker'
      preLoaderRoute: typeof InitiativetrackerImport
      parentRoute: typeof rootRoute
    }
    '/party_setup': {
      id: '/party_setup'
      path: '/party_setup'
      fullPath: '/party_setup'
      preLoaderRoute: typeof PartysetupImport
      parentRoute: typeof rootRoute
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/encounters': typeof EncountersRoute
  '/initiative_player': typeof InitiativeplayerRoute
  '/initiative_tracker': typeof InitiativetrackerRoute
  '/party_setup': typeof PartysetupRoute
  '/preview': typeof PreviewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/encounters': typeof EncountersRoute
  '/initiative_player': typeof InitiativeplayerRoute
  '/initiative_tracker': typeof InitiativetrackerRoute
  '/party_setup': typeof PartysetupRoute
  '/preview': typeof PreviewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/encounters': typeof EncountersRoute
  '/initiative_player': typeof InitiativeplayerRoute
  '/initiative_tracker': typeof InitiativetrackerRoute
  '/party_setup': typeof PartysetupRoute
  '/preview': typeof PreviewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/encounters'
    | '/initiative_player'
    | '/initiative_tracker'
    | '/party_setup'
    | '/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/encounters'
    | '/initiative_player'
    | '/initiative_tracker'
    | '/party_setup'
    | '/preview'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/encounters'
    | '/initiative_player'
    | '/initiative_tracker'
    | '/party_setup'
    | '/preview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  EncountersRoute: typeof EncountersRoute
  InitiativeplayerRoute: typeof InitiativeplayerRoute
  InitiativetrackerRoute: typeof InitiativetrackerRoute
  PartysetupRoute: typeof PartysetupRoute
  PreviewRoute: typeof PreviewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  EncountersRoute: EncountersRoute,
  InitiativeplayerRoute: InitiativeplayerRoute,
  InitiativetrackerRoute: InitiativetrackerRoute,
  PartysetupRoute: PartysetupRoute,
  PreviewRoute: PreviewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/builder",
        "/encounters",
        "/initiative_player",
        "/initiative_tracker",
        "/party_setup",
        "/preview"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/builder": {
      "filePath": "builder.tsx"
    },
    "/encounters": {
      "filePath": "encounters.tsx"
    },
    "/initiative_player": {
      "filePath": "initiative_player.tsx"
    },
    "/initiative_tracker": {
      "filePath": "initiative_tracker.tsx"
    },
    "/party_setup": {
      "filePath": "party_setup.tsx"
    },
    "/preview": {
      "filePath": "preview.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
